### ISSUE TITLE
Asking about an implementation detail: mapping layer between the feature extractor and the Local NN. 

### ISSUE THREAD

**Issue by Zongshun96** [HelloKevin07/AgileNN#1]
Greetings,
The idea of applying XAI techniques to transmission compression is very interesting and promising. Very nice job and congratulations!

I have a question regarding an implementation detail mentioned in your paper. 
In Section 5, you mentioned a mapping layer between the feature extractor and the Local NN, but in your [line1](https://github.com/HelloKevin07/AgileNN/blob/main/train_agilenn.py#L263) and [line2](https://github.com/HelloKevin07/AgileNN/blob/51ddf525670e8d03fb6ca71dad328f32dd30b4d9/models.py#L191), it seems you only randomly pick the first `K_top` without sorting the importances. 
Could you please elaborate further the detail of this mapping layer and how is it trained?

Thanks,
Zongshun

**Comment by HelloKevin07** [comment]
Thanks for your question!

The mapping is a preprocessing step that sorts the output channels of the feature extractor. The channels are sorted by their tendency of spitting out top-k feature maps, when the feature extractor hasn't been trained. In other words, channels that are more likely to spit out important features will be re-indexed to the top-k position. To implement this **in the simplest way**:
1. Cascade the untrained Feature Extractor with the trained Reference NN as a joint model
2. Run the joint model on the entire training set, compute the average importance for each channel
3. Sort the channels with their importances averaged over the training set. You can exchange the corresponding convolution filters' weights to ground such sorting.

Overall, adding this module can reduce learning complexity and sometimes improves training stability, but may contribute **very little** to the final results. That's why I removed it when I cleaned my code and it doesn't appear in the repo.

**Comment by HelloKevin07** [comment]
I have incorporated the [mapping layer](https://github.com/HelloKevin07/AgileNN/blob/main/feature_extractor_prep.py) into the repo just in case you and others really want to see the details.
